spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Tu816gdi*
  jpa:

    show-sql: true
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  sql:
    init:
    #schema-locations: classpath*:db/mysqldb/schema.sql
    #mode: always
# 파라미터 확인을 위한 trace
logging:
  level:
    org.hibernate.type: trace
    org.springframework.security: trace

server:
  port: 8080